---
- name: creating files or directories
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: creating a file
    file:
      path: /home/ansadmin/testfile
      state: touch
      mode: 0755

