---
- name: creating files or directories
  hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: creating a file
    file:
      path: /opt/dir1
      state: directory
      mode: 0755
      owner: ansadmin
